spring:
 mvc:
  static-path-pattern: /static/**
 resources:
  static-locations: classpath:/static/
 thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML
  encoding: UTF-8
  templateMode: HTML5
  servlet.content-type: text/html
  cache: false
 datasource:
  url: jdbc:mysql://localhost:3306/shop
  username: root
  password: root
  driverClassName: com.mysql.jdbc.Driver
#  ssl:
#    key-store: classpath:.keystore
#    key-store-password: quanlei
#    key-store-type: JKS
#    alias: tomcat


#  actuator 配置将所有端口暴露，如不配置只有/health和/info俩个端点
management:
  endpoints:
    web:
      exposure:
        include: "*" # * 在yaml 文件属于关键字



